GET http://localhost:5000/users

###
get http://localhost:5000/users/1

###
post http://localhost:5000/users
Content-Type: application/json

{
    "name": "valent",
    "telephone": "0832138232",
    "email": "valent@example.com"
}
